<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="com.naveenautomationlabs.AutomationFramework.Listeners.CustomListener"/>
    <listener class-name="com.naveenautomationlabs.AutomationFramework.Listeners.ExtentReportListener"/>
    <listener class-name="com.naveenautomationlabs.AutomationFramework.Listeners.TransformerForRetry"/>
  </listeners>
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.naveenautomationlabs.AutomationFramework.Tests.SuccessTest">
        <methods>
          <include name="setUpLogger"/>
          <include name="validateOrderPlacedAfterLogin"/>
          <include name="setUp"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- com.naveenautomationlabs.AutomationFramework.Tests.SuccessTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
